name: cxr-benchmark
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy=1.26.4
  - pandas=2.3.1
  - scikit-learn=1.7.0
  - scipy=1.16.0
  - matplotlib=3.10.3
  - seaborn=0.13.2
  - umap-learn=0.5.6
  - tqdm=4.66.2
  - lightgbm=4.6.0
  - xgboost=3.0.2
  - tensorflow=2.19.0
  - keras=3.10.0
  - shapely=2.1.1
  - pydicom=3.0.1
  - jupyterlab=4.4.4
  - ipywidgets=8.1.7
  - pip
  - pip:
      - tensorflow-hub==0.16.1
      - tensorflow-text==2.19.0
      - google-cloud-storage==2.19.0
      - google-cloud-bigquery==3.35.0
      - google-api-python-client==2.176.0
      - google-auth==2.40.3
      - google-cloud-aiplatform==1.103.0
